### ISSUE TITLE
Editar cartão

### ISSUE THREAD

**Issue by mauriciomelo** [retroboard/board#13]
Após criado, devemos conseguir editar um cartão

**Comment by ThaisaMirely** [comment]
Critérios de aceitação proposto:
1) qualquer cartão pode ter seu conteúdo editado por qualquer pessoa que tenha acesso ao board;

Modelo de exemplo de interface para o cartão, contendo icones de votação, editar e excluir carão.
https://y3vr5jl1rj.codesandbox.io
