### ISSUE TITLE
Checar vulnerabilidades das dependências 

### ISSUE THREAD

**Issue by mauriciomelo** [retroboard/board#5]
**objetivo:**  automatizar o processo de checagem de vunerabilidades nas dependências do projeto no processo de build no CI.

**o que precisa ser feito:**
- [ ] adicionar estágio no pipeline do CI para checagem de dependências com NPM audit

**Comment by fernando-alves** [comment]
Oi @ThaisaMirely @mauriciomelo 

O comando `audit` só está disponível a partir da versão [6](https://blog.npmjs.org/post/173260195980/announcing-npm6), enquanto o projeto usa a `5.6.0`. Até onde eu sei, podemos fazer um dos seguintes:
- Usar outro modulo para a verificação
- Atualizar o nodejs para uma versão 10+
- Atualizar apenas o npm para uma versão 6+

Vocês tem alguma outra sugestão? Não sou particularmente fã da primeira, qualquer uma das outras funciona para mim.

**Comment by mauriciomelo** [comment]
@fernando-alves  atualizar o nodejs para a versão 10+ parece ser uma boa, não vejo nenhum problema

**Comment by fernando-alves** [comment]
Massa!

Abri um PR atualizando e quando ele passar eu mando o outro com a mudança no build.
